### ISSUE TITLE
Functionality description

### ISSUE THREAD

**Issue by star-buck** [plasma-extensions/plasma-widget-bladerunner#1]
![windows_10_cortana_review](https://cloud.githubusercontent.com/assets/840070/15627373/10b5f8d4-24e2-11e6-96a4-e1c60060878a.jpg)

**Comment by UriHerrera** [comment]
Krunner is definitely an unappreciated tool. I'll make a mockup.

**Comment by UriHerrera** [comment]
![](http://i.imgur.com/tlUGE5z.png)
![](http://i.imgur.com/9Qzgoyq.png)
![](http://i.imgur.com/MJD2fxn.png)

# 

After watching some review videos of Cortana I made this mockup. In the first image the widget is activated when the user clicks and reveals a search history. In the second and third images upon searching for something the user gets results divided in the next 4 tabs: Application and commands, Files and Folders, Arithmetic operations, Bookmarks.

I added the tabs because in Krunner when searching for anything it displays all the results, all at once and it gets kind of messy so while Krunner can do a lot more than what these tabs would display, these tabs conform the most common uses of Krunner.

**Comment by azubieta** [comment]
It looks great ! I already want to use it :) !
So the idea is to embed Krunner into the panel or we are going to reuse one of the existent launchers?

**Comment by star-buck** [comment]
have a widget kalled krunner-widget that reuses krunner as base, just makes it placeable on the desktop or in the panel like any other widgets.

As a sidenote, maybe this is also interesting: http://cukic.co/2016/05/31/voy-message-passing-library-for-distributed-krunner/
